[normal]
autostartup = true

[theme]
theme = "system"
accent_color = "#0078D4"
follow_system_accent = false

[console]
encoding = "ANSI"

[download]
source = "FastMirror镜像源"
aria2_enabled = true
aria2_threads = 6

[instance]
auto_accept_eula = false
auto_restart_on_crash = false


